### ISSUE TITLE
Remove Basic Renderer

### ISSUE THREAD

**Issue by pigne** [graphstream/gs-ui-swing#1]
Since The Full renderer is fully functional,   `basicRenderer` is no longer needed.

**Comment by gsavin** [comment]
Maybe a rename of `SwingFullGraphRenderer` to `SwingGraphRenderer` should be done with this removal?

**Comment by hichbra** [comment]
Removal of SwingBasicGraphRenderer https://github.com/graphstream/gs-ui-swing/commit/6468606f78cc829496a6f5632b8c9f88776579b3 and SwingFullGraphRenderer renaming https://github.com/graphstream/gs-ui-swing/commit/94532424e7716db627adaff74e3835ba777cf0e4.
