### ISSUE TITLE
DefaultView is not abstract and does not override abstract method enableMouseOptions()

### ISSUE THREAD

**Issue by jboydon** [graphstream/gs-ui-swing#6]
Hello,  tried to compile it against the master branch of gs libraries and I have got this error:

`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project gs-ui-swing: Compilation failure
[ERROR] /Users/xxx/Development/Tests/GraphStream/gs-ui-swing/src/org/graphstream/ui/swing_viewer/DefaultView.java:[114,8] org.graphstream.ui.swing_viewer.DefaultView is not abstract and does not override abstract method enableMouseOptions() in org.graphstream.ui.view.View
`
regards
  john

**Comment by hichbra** [comment]
Hi!

You need to use gs-core 2.0+ to use the gs-ui packages.

**Comment by jboydon** [comment]
Solved with 2.0.0-beta
