### ISSUE TITLE
Can't get input stream from URL! (file:///home/hicham/Bureau/b.png)

### ISSUE THREAD

**Issue by jboydon** [graphstream/gs-ui-swing#7]
Test case: DemoViewerJComponents execution cause:

`Dec 12, 2019 1:01:07 PM org.graphstream.ui.swing.util.ImageCache loadImage
WARNING: file:///home/hicham/Bureau/b.png
javax.imageio.IIOException: Can't get input stream from URL!
`

**Comment by hichbra** [comment]
As your exception said, if you want to run this test, you must replace the uri of the png file by your own.
